config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'about' => "static#about"
  root 'posts#index'
  resources :posts do
    resources :comments
    resources :upvotes, only: :create
    resources :downvotes, only: :create
  end

  resources :users, only: :show # for users_controller 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :text, :user_id, :post_id, presence: true

  delegate :name, to: :user, prefix: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  
  mount_uploader :photo, PhotoUploader

  # Using law of demeter for loose coupling
  delegate :photo, :name, to: :user, prefix: true

  validates :photo, :description, :user_id, presence: true
  
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :photo, PhotoUploader
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller? #whitelist photo and name

  protect_from_forgery with: :exception

  # for whitelisting purposes
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name, :photo) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :name, :photo) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :if_not_owner_redirect_to_root, only: :destroy #to prevent automated DELETE req from deleting the content
  before_action :authenticate_user!, only: :create  

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
    if @comment.valid?
      redirect_to root_path
    else
      flash[:error] = "Invalid attributes."
      redirect_to root_path
    end
  end

  def destroy
    @comment = Comment.find(params[:id]) #id here refers to the comment id
    @comment.destroy
    redirect_to root_path
  end

  private 

  def if_not_owner_redirect_to_root
    @comment = Comment.find(params[:id])
    if @comment.user != current_user
      redirect_to root_path
    end
  end

  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end

end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController
  before_action :authenticate_user! 

  def create
    @post = Post.find(params[:post_id])
    @post.unliked_by current_user
    
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :if_not_owner_redirect_to_root, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.all.order('created_at DESC').includes(:user, comments: :user)

  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.create(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def if_not_owner_redirect_to_root
    redirect_to root_path if Post.find(params[:id]).user != current_user
  end

  def post_params
    params.require(:post).permit(:user_id, :photo, :description)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :authenticate_user! 

  def create
    @post = Post.find(params[:post_id])
    @post.liked_by current_user
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js {}
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/downvotes/create.js.erb
$('#likes-container-<%= @post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: { post: @post } %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'instagram.ico' %>
  <title>Share Your Photos Online - Instapost</title>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div id="wrap">
    <%= render 'shared/nav' %>
    <div class = "container-fluid">
      <div class = "row">
        <div class = "col-xs-12 col-md-8 col-md-offset-2">
          <%= render 'shared/flash' %>
          <%= yield %>
        </div>
      </div>
    </div>  
  </div> <!-- #Wrap -->
    
  <%= render 'shared/footer' %>

</div>
<%#= console %>
</body>
</html>

app/views/posts/_likes.html.erb
<% if user_signed_in? %>
  <span class="post-like">
    <% if current_user.voted_up_on? post %>
      <%= link_to '<i class="fa fa-heart" aria-hidden="true"></i>'.html_safe, post_downvotes_path(post.id), method: :post, remote: true %> 
    <% else %>
      <%= link_to '<i class="fa fa-heart-o" aria-hidden="true"></i>'.html_safe, post_upvotes_path(post.id), method: :post, remote: true  %>
    <% end %>

    <%= pluralize post.get_likes.size, "like" %>
  </span>
<% else %>
  <span class="post-like">
    <i class="fa fa-heart-o" aria-hidden="true"></i> <%= pluralize post.get_likes.size, "like" %>
  </span>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= simple_form_for @post, method: :patch do |f| %>
  <%= f.input :photo %>
  <%= f.input :description %>
  <%= f.submit 'Update', class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/index.html.erb
<div class="wrapper">
<% @posts.each do |post| %>
  
  <div class="post-box">

    <div class="post-header">
      <!-- <div class="prof-pic-container"> -->
        <a href="<%= user_path(post.user) %>" class="prof-pic-container">
          <%= image_tag post.user_photo, class: 'prof-pic-small img-circle' %>
        </a>
      <!-- </div> -->
      <div class="prof-name-container">
        <%= link_to post.user_name, user_path(post.user_id), class: "uname" %>
      </div>
      <a class="timestamp pull-right" href="#"><%= distance_of_time_in_words(DateTime.now, post.created_at) %></a> 
    </div>

    <%= image_tag post.photo, class: 'photo' %>
    
    <div class="post-body">
      
      <%= link_to post.user_name, user_path(post.user_id), class: "uname" %> <%= post.description %>

    </div>
    <!-- <hr> -->
    <div class="post-comments">

      <% post.comments.each do |comment| %>
        
        <p><%= link_to comment.user_name, user_path(comment.user_id), class: "uname" %> <%= comment.text %></ p>

      <% end %>


      <hr>

      
      <span id="likes-container-<%= post.id %>">
        <%= render partial: 'likes', locals: {post: post} %>
      </span>

      <% if user_signed_in? %>
        <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post do |f| %>
          <%= f.input :text, label: 'Comment', placeholder: 'Add a comment...' %>
          <%= f.submit 'Post', class: 'btn btn-primary btn-block', remote: true %>
        <% end %>
      <% end %>
    </div>
  </div>

<% end %>
</div>

app/views/posts/new.html.erb
<h2>Your details please</h2>
<%= simple_form_for @post do |f| %>
  <%= f.input :photo %>
  <%= f.input :description %>
  <%= f.submit "Post", class: "btn btn-default btn-block" %>
<% end %>

app/views/posts/show.html.erb
<%= image_tag @post.user.photo %>
<%= @post.user.name %>
<%= image_tag @post.photo %>
description: <%= @post.description %>

<% if @post.user == current_user %>
  <%= link_to 'Edit Post', edit_post_path(@post) %>
  <%= link_to 'Delete Post', @post, method: :delete %>
<% end %>

<% @comments.each do |comment| %>
Username: <%= comment.user.name %>
Comment: <%= comment.text %> <br>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <p><span>© Srijal Joshi</span> <%= Date.today.year %> All Rights Reserved</p>
</div>

app/views/shared/_nav.html.erb
    <nav class="container-fluid">
      <div class="row">
        <div class = "col-lg-6 col-lg-offset-3">
          <div class="row">
            <div class="nav-wrapper">

              <div class="col-xs-6">
                <span class="pull-left brand"><%= link_to icon('instagram'), root_path, class: "fa-lg" %> &nbsp;  <%= link_to 'Instapost', root_path %></span>
              </div>

              <div class="col-xs-6">
                <% if user_signed_in? %>
                <span class="nav-links pull-right"><%= link_to icon('plus-circle'), new_post_path %></span>
                <span class="nav-links pull-right"><%= link_to icon('wrench'), edit_user_registration_path %></span>
                <span class="nav-links pull-right"><%= link_to icon('sign-out'), destroy_user_session_path, method: :delete, class: "fa-lg"  %></span>
                <% else %>
                <span class="nav-links pull-right"><%= link_to icon('user-plus'), new_user_registration_path, class: "fa-lg" %></span>
                <span class="nav-links pull-right"><%= link_to icon('sign-in'), new_user_session_path, class: "fa-lg"  %></span>
                <% end %>
              </div>

            </div>
          </div>
        </div>
      </div>
    </nav>

app/views/upvotes/create.js.erb
$('#likes-container-<%= @post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: { post: @post } %>")

app/views/users/show.html.erb
<div class="prof-wrapper">
<div class="prof_header">

  <div class="row">
    <div class="header-wrapper">

      <div class="col-xs-4">
        <%= image_tag @user.photo, class: 'prof_pic' %>
      </div>

      <div class="col-xs-8">

        <div class="user_header">

          <div class="row">
            <div class="col-xs-6">
              <h1 class = "username"><%= @user.name %></h1>
        <span class="count"><%= @user.posts.count %> posts</span> 
            </div>

            <div class="col-xs-6">
              <%= link_to 'EDIT PROFILE', edit_user_registration_path(@user), class: 'user_edit_button btn btn-default' if user_signed_in? && @user == current_user %>
            </div>
          </div>  
        </div>


      </div>
    </div>

  </div>

</div>


<div class="prof_post_box">

  <div class="posts-wrapper">
    <div class="row">
    <% @user.posts.each do |post| %>

        <div class="col-xs-4">
          <%= image_tag post.photo, class: 'prof_show' %>
        </div>

    <% end %>
    </div>

  </div>
</div>
</div>